name: aipnd
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - python=3.6.6
  - requests
  - matplotlib
  - pytorch=0.4.1
  - torchvision=0.2.1
  - ipython=6.5.0
  - jupyter
  - jupyter_contrib_nbextensions
  - jupyter_nbextensions_configurator
  - notebook=5.6.0
  - numpy

